info:
  contact: {}
paths:
  /customers:
    get:
      consumes:
      - application/json
      parameters:
      - description: Customer ID
        in: path
        name: id
        required: true
        type: integer
      responses: {}
      tags:
      - Customer
swagger: "2.0"
